feat(rad-1266): bump versions for advanced tagger (v3.1, v4.7, v5.1)
AYLIEN/apis pull request #74
Opened 2021-09-17 12:41 UTC by FrontSide

2021-09-18 07:23 UTC, marcinaylien requested changes

2021-09-18 07:23 UTC, marcinaylien commented on scripts/github-release.sh
> +  echo 'Version to release is required! ex. ./github-release.sh "advanced tagger support" 4.7.2 or ./github-release.sh "advanced tagger support" 5.1.0'
you added a text specific to advanced tagger to generic script

2021-09-18 07:23 UTC, marcinaylien commented on scripts/github-release.sh
> +  git push origin master
please do not push to master!
the script was made to push to release branch on purpose in order to create a PR first. Thanks to that you can review your PR first carefully and find a possible bug. We found many this way...

2021-09-18 07:24 UTC, marcinaylien commented on aylien/v1/news/api-docs.yaml
> +  version: "3.1"
version in v1 is unused...

2021-09-20 08:12 UTC, FrontSide commented on scripts/github-release.sh
> +  echo 'Version to release is required! ex. ./github-release.sh "advanced tagger support" 4.7.2 or ./github-release.sh "advanced tagger support" 5.1.0'
It's an example. IMHO it's better to give a real world example instead of some abstract placeholders.

2021-09-20 08:13 UTC, FrontSide commented on scripts/github-release.sh
> +  git push origin master
Really? That's reviewing 8 PRs, each with 100s of lines of autogenerated code. I mean I guess we can but I would have thought it's more valuable to do thorough testing.

2021-09-20 08:15 UTC, FrontSide commented on aylien/v1/news/api-docs.yaml
> +  version: "3.1"
My understanding was that we use it internally. Either way, I will remove the package configs for this version but keep the API specs.

2021-09-20 08:21 UTC, marcinaylien commented on scripts/github-release.sh
> +  git push origin master
Yeah, you can do mistakes in versions,  commits messages, in apis.... Well, I did and I found them when doing PR.

2021-09-20 08:25 UTC, FrontSide commented on scripts/github-release.sh
> +  git push origin master
Fair enough, I'll switch it back to push to a branch

2021-09-20 08:44 UTC, marcinaylien approved these changes

2021-09-21 07:26 UTC, marcinaylien approved these changes

2021-09-21 07:42 UTC, merged